alias jpost="curl -X POST -H 'Content-Type: application/json' -d"
alias jput="curl -X PUT -H 'Content-Type: application/json' -d"

# Dotfiles framework warnings
if [[ $- == *i* ]]; then # In non-interactive shells $PS1 is not set
  # Download the updates
  pushd $HOME/.dotfiles > /dev/null
  # { git fetch & disown; } 2>/dev/null

  if [[ "$(git status -s)" != "" ]]; then
    warn "There are uncommitted changed to dotfiles"
  fi

  if [[ "$(git name-rev --name-only HEAD)" != "master" ]]; then
    warn "Dotfiles are in development mode"
  elif [[ "$(git rev-parse origin/master)" != "$(git rev-parse master)" ]]; then
    warn "Updates available for dots. Run pushd ~/.dotfiles; git pull; popd"
  fi
  popd > /dev/null
fi
