# Initialize the default nix profile
if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then
  . ~/.nix-profile/etc/profile.d/nix.sh;

  if [ -e /etc/ssl/cert.pem ]; then
    export NIX_SSL_CERT_FILE="/etc/ssl/cert.pem"
  fi
fi

if [[ -f $HOME/.bashrc && $- == *i* ]]; then
   source $HOME/.bashrc
fi

export PATH="$HOME/.cargo/bin:$PATH"
PATH=/Users/teverding/.hv_bin:${PATH}
