language: c

sudo: required

matrix:
  include:
  - {os: linux, dist: trusty}
  - {os: osx, osx_image: xcode8.3}

before_install:
  - docker pull ubuntu:16.04
  - docker run -it ubuntu bash

script:
- docker run -it ubuntu 'setup.sh && source .bash_profile'
