name: CI Suite

on: [push]

jobs:
  build:
    name: Build Korolev
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
    - name: git checkout
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: nix build
      run:
        nix build -L '.#nixosConfigurations.korolev.config.system.build.toplevel'

    - name: nix shell
      run:
        nix develop --command 'true'
