name: CI Suite

on: [push]

jobs:
  installation_test:
    name: Installs
    runs-on: ${{ matrix.os }}
    timeout-minutes: 4

    steps:
    - name: git checkout
      uses: actions/checkout@v2

    - name: Create existing configuration
      run: mkdir -p ${HOME}/.github && touch ${HOME}/.github/README.md

    - name: Install dotfiles
      run: cat bin/dot | bash -x

    - name: Backups existing configuration
      # No outer quotes since wc -l on BSD has leading whitespace
      run: test $(find "${HOME}" -iname 'dotfile-conflicts*' | wc -l) == "1"

    - name: Can `dot` around
      run: ${HOME}/bin/dot status

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

  dotfiles_test:
    name: "Script: dotfiles"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8

    steps:
    - name: git checkout
      uses: actions/checkout@v2

    - name: Install dotfiles
      run: cat bin/dot | bash -x

    - name: Add ~/bin to path
      run: echo "${HOME}/bin" >> "${GITHUB_PATH}"

    - name: Run updates
      run: dotfiles autorun

    - name: Verify reset
      run: dotfiles reset

    - name: Verify idempotence
      run: dotfiles autorun

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
